### ISSUE TITLE
Can't deploy multiple times in same AWS account/region

### ISSUE THREAD

**Issue by jagomsim** [elastic/elastic-serverless-forwarder#150]
When deploying twice, with any method (e.g., AWS console), the second deploy fails. A real case scenario could be to deploy one for staging and another for production, while keeping changes in a Git repo.
The second deploy throws error when creating the `ElasticServerlessForwarderEventMacro` resource. Within that resource, the error is that `elastic-serverless-forwarder-macro already exists in stack`. It is thrown because the first deploy already creates a macro with that exact name.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 1.2.1
- Steps to Reproduce:
  - In one AWS Account/Region, try to deploy the application twice.

**Comment by aspacca** [comment]
hello @jagomsim 

this is unluckily a known problem due to a limitation on the underlying cloudformation template we use to publish the forwarder on the aws serverless application repository.

we have two nested application in the main cloudformation template: one for the macro and one for the effective forwarder application.

the macro takes care of parsing the cloudformation parameters (the various ARNs of the inputs etc etc) and transforming the cloudformation template of the forwarder application to include the relevant source events resources and iam policies for the lambda.

the best solution would be to use an ID of the macro generated uniquely and dynamically from a cloud formation function, like we do for the continuing and the replay queues. while this is possible, it's not possible to use as `Name` of a `Fn::Transform` the result of a function (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-transform.html), so even if we generate such an ID we could not reference it in the `Fn::Transform`.

A workaround is to deploy in a different region

**Comment by jagomsim** [comment]
Hello @aspacca, thanks for the quick answer!
Then we would look into deploying in a different region.

**Comment by aspacca** [comment]
@jagomsim you can now use the following method to publish multiple ESF lambdas: https://www.elastic.co/guide/en/observability/current/aws-deploy-elastic-serverless-forwarder.html#aws-serverless-forwarder-direct-deploy

**Comment by vijaysraju** [comment]
> [@jagomsim](https://github.com/jagomsim) you can now use the following method to publish multiple ESF lambdas: https://www.elastic.co/guide/en/observability/current/aws-deploy-elastic-serverless-forwarder.html#aws-serverless-forwarder-direct-deploy

Did the CloudFormation or direct deployment methods work successfully for multiple deployments?
