### ISSUE TITLE
[Question] S3-SQS input & deploy/config

### ISSUE THREAD

**Issue by PeterPaulH** [elastic/elastic-serverless-forwarder#170]
LS,
I am looking at deploying the elastic-serverless-forwarder but I have two questions (Is this the correct place for those questions ?)
As a start we will look at using the S3-SQS input as a replacement for our current lambda function.

We could deploy the elastic-serverless-forwarder and consume messages from s3-sqs. But ...
if we add an extra S3-Bucket to send messages to that SQS, do we need to redeploy/reconfigure the elastic-serverless-forwarder ?
(assuming the permissions for the lambda to access the extra S3-Bucket is in place)

Why do we need to specify ElasticServerlessForwarderS3Buckets in the deployment of the lambda ?
In our AWS setup the permissions on the bucket are handled by the owner of the bucket and not by the owner of this lambda.

Greetings,
PeterPaul

**Comment by aspacca** [comment]
hello @PeterPaulH 

you can ask question about the forwarder in the [forum](https://discuss.elastic.co/c/observability/82), but it's no problem answering your question here :)

`ElasticServerlessForwarderS3Buckets` are requested so that the Cloudformation template can set the proper IAM policies only for the specific S3 Buckets the forwarder needs to access.

In general you don't need to manage specific IAM resources for the forwarder and everything will be taken care when deploying it from the Cloudformation template.

So, if you have an SQS queue, and you will add a new S3 bucket to send notification to that queue, the forwarder needs to be redeployed adding the new S3 bucket in the list of `ElasticServerlessForwarderS3Buckets` so that the lambda will have the proper permission for the new bucket.

At the contrary, if you manage your own IAM policies and have already added the proper permission for the new S3 bucket you don't  need to redeploy the forwarder.
Beware anyway that's not the suggested and supported way of deploying and managing the forwarder, since it could end up in misconfiguration and improper permissions.

**Comment by PeterPaulH** [comment]
Thanks for the answers.
This was exactly what I was hoping for ;-)
