### ISSUE TITLE
Refactor handler unit / integration tests

### ISSUE THREAD

**Issue by girodav** [elastic/elastic-serverless-forwarder#184]
**Describe the enhancement:**

[test_handler.py ](https://github.com/elastic/elastic-serverless-forwarder/blob/main/tests/handlers/aws/test_handler.py), that includes unit and integration tests for the Lambda handler, is almost 4000 lines of code and I find it hard to maintain. I propose to refactor it into multiple, purpose-specific, python test files. As first step, I would split unit and integration tests into 2 different files, and iterate on that where we see fit

**Comment by endorama** [comment]
Moving here some discussion I had with @girodav and @aspacca on how to improve the situation.

1. Tests share setup code by inheriting from the same base class. This makes hard to distinguish which setup code is used for which test. By extracting functionalities from this single setup function we can then leverage composition over inheritance to split the single setup in multiple setups with shared logic.
2. Writing helper functions that do not leverage a global state (i.e. `_mock_awsclient`) but get state through function arguments. This would allow to reuse the same logic by changing the underlying actors.
3. Leverage `subTest` to group test with same setup code (helps with (1) too)
4. Leverage testcontainers-py library to wrap test containers we need to use (localstack, elasticsearch, logstash). This library provides an easier to use API and allows for moving bootstrap code for related services out of tests files/setup functions.
5. Implement file fixture loading through some conventions, to load test and config data from files instead of writing them in variables. This helps reusing the same data.
6. Add suite setup code to bootstrap shared underlying testing infrastructure (i.e. localstack). To implement this all test need to make sure to use only resources created by them (i.e. S3 buckets) and not affect shared resources. By using `type(self).__name__` is possible to use the class name as part of related resources name to achieve this.

**Comment by aspacca** [comment]
> 6\. Add suite setup code to bootstrap shared underlying testing infrastructure (i.e. localstack). To implement this all test need to make sure to use only resources created by them (i.e. S3 buckets) and not affect shared resources. By using `type(self).__name__` is possible to use the class name as part of related resources name to achieve this.

can you clarify on this?

**Comment by aspacca** [comment]
> 3\. Leverage `subTest` to group test with same setup code (helps with (1) too)

do you mean replacing current `test_lambda_handler_continuing`/`test_lambda_handler_replay` with `subTest` instead?
I'd rather go the other way and remove `subTest` everywhere where possible, or in case replace with https://pypi.org/project/pytest-subtests/

**Comment by aspacca** [comment]
> 2\. Writing helper functions that do not leverage a global state (i.e. `_mock_awsclient`) but get state through function arguments. This would allow to reuse the same logic by changing the underlying actors.

can you expand on this?
for `_mock_awsclient` we have both cases: global state `storage.S3Storage._s3_client`, but that's basically only that. the othercases are wrapping aws client getter helper functions (`handlers.aws.handler.get_sqs_client`, `handlers.aws.utils.get_sqs_client`, `handlers.aws.utils.get_cloudwatch_logs_client`, etc etc)

are you referring to this or to something else? :)

**Comment by aspacca** [comment]
closed by #260
