### ISSUE TITLE
Add support for Private VPC Config

### ISSUE THREAD

**Issue by aspacca** [elastic/elastic-serverless-forwarder#187]
**Describe the enhancement:**

**Describe a specific use case for the enhancement or feature:**

**Comment by jamieparkinson** [comment]
Just a note to say this addition will be much appreciated!

**Comment by saurabh-amcs** [comment]
I followed below steps
1. Modified IAM role of the main function not micro with policies from role ` AWSLambdaVPCAccessExecutionRole  `
2. Created a gateway endpoint to s3 in vpc (I was using s3 to fetch CloudTrail logs but even to fetch config it would need this, I think, as the function won't be able to reach s3 using the public url.)
3. Put the function in vpc from configuration section of the main lambda function. VPC of my Elasticsearch instance.
4. Changed config to access elastic using private url instead of the public.

PS - Since the IAM role is now tinkered , Cloud Formation won't be able to delete the stack , need to remove the policies first.

Unfortunately I can't make it work with cloud watch - when it is used function throws timeout error and the warning 
`FutureWarning: The sqs client is currently using a deprecated endpoint:`

**Comment by aspacca** [comment]
hello @saurabh-amcs 

> PS - Since the IAM role is now tinkered , Cloud Formation won't be able to delete the stack , need to remove the policies first.

yes, this is a limitation on AWS CF and there's nothing we can do about it.
Anyway when we'll release direct support for VPC, `AWSLambdaVPCAccessExecutionRole` role will be attached automatically to the Forwarder role so you won't need anymore to tinker the role

> Unfortunately I couldn’t make it work with cloud watch - lambda throws timeout error and the warning `FutureWarning: The sqs client is currently using a deprecated endpoint:`

is the endpoint printed in the error message? could you share it?
I cannot reproduce the issue in the current development branch that will add support for VPC.
I will try later with the current public version.

**Comment by saurabh-amcs** [comment]
> yes, this is a limitation on AWS CF and there's nothing we can do about it.

correct I understand that. That's not the issue I wanted to report. It was a breadcrumb for anyone who is trying to do it.

> is the endpoint printed in the error message? could you share it?

Please refer to the issue for more details- https://github.com/elastic/elastic-serverless-forwarder/issues/192

> I cannot reproduce the issue in the current development branch that will add support for VPC.

You are right about this too. When I used the `main` branch of the repo I didn’t see the warning. However the timeout error is still there so deprecated endpoint must not be causing it which I had thought earlier could be the reason.

**Comment by aspacca** [comment]
requirements for deploying in a VPC are added to the documentation: https://github.com/elastic/observability-docs/pull/2473
support for deployment in a VPC was added at https://github.com/elastic/elastic-serverless-forwarder/pull/201
