### ISSUE TITLE
Timeout error when used in VPC

### ISSUE THREAD

**Issue by saurabh-amcs** [elastic/elastic-serverless-forwarder#192]
- Version: 1.5
- Steps to Reproduce:

1. Modified IAM role of the main function not micro with policies from role ` AWSLambdaVPCAccessExecutionRole  `
2. Created a gateway endpoint to s3 in vpc (I was using s3 to fetch CloudTrail logs.)
3. Put the function in vpc from configuration section of the main lambda function. VPC of my Elasticsearch instance.
4. Changed config to access elastic using private url instead of the public.

This works well with CloudTrail!

But I can't make it work with cloud watch - when it is used function throws timeout error and the warning 
`FutureWarning: The sqs client is currently using a deprecated endpoint:` 

So I tried to create a VPC endpoint for SQS because I thought it was not able to reach the SQS from VPC just like it couldn’t reach s3 from lambda in VPC for this I had to create gateway type endpoint in vpc.

The similar config (with public url) works when lambda is not in vpc. 

error - 
`Connect timeout on endpoint URL: "https://us-west-1.queue.amazonaws.com/"`

Stack trace 
```

File "/var/task/handlers/aws/utils.py", line 83, in wrapper
return func(lambda_event, lambda_context)
File "/var/task/handlers/aws/handler.py", line 507, in lambda_handler
composite_shipper.flush()
File "/var/task/shippers/composite.py", line 94, in flush
shipper.flush()
File "/var/task/shippers/es.py", line 225, in flush
self._handle_outcome(errors=errors)
File "/var/task/shippers/es.py", line 177, in _handle_outcome
self._replay_handler("elasticsearch", self._replay_args, action_failed[0])
File "/var/task/handlers/aws/utils.py", line 364, in replay_handler
sqs_client.send_message(
File "/var/task/botocore/client.py", line 507, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/task/botocore/client.py", line 926, in _make_api_call
http, parsed_response = self._make_request(
File "/var/task/botocore/client.py", line 949, in _make_request
return self._endpoint.make_request(operation_model, request_dict)
File "/var/task/botocore/endpoint.py", line 119, in make_request
return self._send_request(request_dict, operation_model)
File "/var/task/botocore/endpoint.py", line 202, in _send_request
while self._needs_retry(
File "/var/task/botocore/endpoint.py", line 354, in _needs_retry
responses = self._event_emitter.emit(
File "/var/task/botocore/hooks.py", line 412, in emit
return self._emitter.emit(aliased_event_name, **kwargs)
File "/var/task/botocore/hooks.py", line 256, in emit
return self._emit(event_name, kwargs)
File "/var/task/botocore/hooks.py", line 239, in _emit
response = handler(**kwargs)
File "/var/task/botocore/retryhandler.py", line 207, in __call__
if self._checker(**checker_kwargs):
File "/var/task/botocore/retryhandler.py", line 284, in __call__
should_retry = self._should_retry(
File "/var/task/botocore/retryhandler.py", line 320, in _should_retry
return self._checker(attempt_number, response, caught_exception)
File "/var/task/botocore/retryhandler.py", line 363, in __call__
checker_response = checker(
File "/var/task/botocore/retryhandler.py", line 247, in __call__
return self._check_caught_exception(
File "/var/task/botocore/retryhandler.py", line 416, in _check_caught_exception
raise caught_exception
File "/var/task/botocore/endpoint.py", line 281, in _do_get_response
http_response = self._send(request)
File "/var/task/botocore/endpoint.py", line 377, in _send
return self.http_session.send(request)
File "/var/task/botocore/httpsession.py", line 490, in send
raise ConnectTimeoutError(endpoint_url=request.url, error=e)

```

**Comment by saurabh-amcs** [comment]
It throws exception on  `sqs_client.delete_message(QueueUrl=queue_url, ReceiptHandle=receipt_handle)`

<img width="740" alt="image" src="https://user-images.githubusercontent.com/117715587/208242627-6573e919-2777-471b-acba-23bd40a7e55b.png">
But I can see in the delete function url is correct
<img width="617" alt="image" src="https://user-images.githubusercontent.com/117715587/208242643-17d5947f-158f-4fbb-9839-e40689745557.png">

I wonder how does it access sqs using `https://us-west-1.queue.amazonaws.com/"`

Is the version published on the serverless repo same as the one tagged 1.5 on Github?

**Comment by saurabh-amcs** [comment]
UPDATE - I don't see the warning when I use main branch to deploy it.
Further this is an issue only when Cloudwatch is used. With s3 same setup works without running into any issues.

**Comment by aspacca** [comment]
hello @saurabh-amcs 

I tested the latest published version (1.5.0) and I needed only an s3 and an sqs vpc endpoint.

You can also use a nat gateway instead.

Is your VPC with a private link?

The version published on the serverless repo is the same as the one tagged on 1.5 on github, but as you can see boto requirement is not pinned at a specific version (https://github.com/elastic/elastic-serverless-forwarder/blob/lambda-v1.5.0/requirements.txt#L3). this means the actual version used was resolved at the moment of publishing the on serverless repo. I've checked and it is v1.25.2

We'll change this behaviour in order to be able to identify the exact direct dependency version

> But I can't make it work with cloud watch - when it is used function throws timeout error and the warning
> FutureWarning: The sqs client is currently using a deprecated endpoint:

this is just a warning from boto3 that is resolved already in newer release, as you found out testing the main branch

> But I can see in the delete function url is correct
> I wonder how does it access sqs using `https://us-west-1.queue.amazonaws.com/"`

the url we are using does not come from `get_queue_url_from_sqs_arn`
it's rather this one: https://github.com/elastic/elastic-serverless-forwarder/blob/lambda-v1.5.0/handlers/aws/utils.py#L353

Could you check which value do you have for the ENV variable `SQS_REPLAY_URL` in the deployed lambda forwarder?

please note that reaching the replay queue means the ingestion failed on elasticsearch. this will require further investigation.


> Further this is an issue only when Cloudwatch is used

how many input type do you have?
could you share your current config yaml, properly anonymised?

as we saw the problem resides in the url of the replay queue, it's were events failed to be ingested are routed for future replay. if the url is wrong in the ENV variable, every event failed to be ingested, regardless of the input type (cloudwatch, kinesis, etc) will hit this error. if you have only events that are failed to be ingested from a cloudwatch input, and not from other type of input, it's rather strange.

(please, if possible don't post images of text as they are hard to read, may not display correctly for everyone, and are not searchable)

**Comment by aspacca** [comment]
hello @saurabh-amcs 

> I created S3 gateway and SQS endpoint - however not sure if latter is required because I am using `s3-sqs` type without it and I can see the logs flowing in it stops when I use type `cloudwatch-logs` logs

as identified by @zmoog at https://github.com/elastic/elastic-serverless-forwarder/issues/197 an SQS endpoint is always required, since the forwarder handle continuation and failures through two sqs queues (the continuing and the replay one)

once we'll publish the next version of the forwarder with explicit support for vpc settings, all the requirements will be documented

**Comment by aspacca** [comment]
requirements for deploying in a VPC are added to the documentation: https://github.com/elastic/observability-docs/pull/2473
support for deployment in a VPC was added at https://github.com/elastic/elastic-serverless-forwarder/pull/201
