### ISSUE TITLE
Unstable tests

### ISSUE THREAD

**Issue by cachedout** [elastic/elastic-serverless-forwarder#27]
Hello,

It looks like there are a few unstable tests in the new pipeline for this project:

https://beats-ci.elastic.co/view/All/job/Library/job/elastic-serverless-forwarder-mbp/job/main/4/testReport/junit/tests.storage.test_s3/TestS3Storage/test_get_by_lines/

and

https://beats-ci.elastic.co/view/All/job/Library/job/elastic-serverless-forwarder-mbp/job/main/5/testReport/junit/tests.handlers.aws.test_handler/TestLambdaHandlerSuccess/test_lambda_handler/

We're now monitoring the health of this pipeline so if these could be cleaned up, it would be terrific. Thanks!

**Comment by aspacca** [comment]
hello @cachedout 

https://beats-ci.elastic.co/view/All/job/Library/job/elastic-serverless-forwarder-mbp/job/main/4/testReport/junit/tests.storage.test_s3/TestS3Storage/test_get_by_lines/ was due to a bug making the test floating. it was fixed in https://github.com/elastic/elastic-serverless-forwarder/pull/26

https://beats-ci.elastic.co/view/All/job/Library/job/elastic-serverless-forwarder-mbp/job/main/5/testReport/junit/tests.handlers.aws.test_handler/TestLambdaHandlerSuccess/test_lambda_handler/ fails due to containers the test connects to (usually elasticsearch one) not being available.

I wait in the tests for the containers be up and in ready state for the underlying applications but I guess after that check the containers die or something similar

any hints on how to solve the problem would be welcome :)

**Comment by cachedout** [comment]
> any hints on how to solve the problem would be welcome :)

Maybe change [this](https://github.com/elastic/elastic-serverless-forwarder/blob/main/tests/handlers/aws/test_handler.py#L183) to [use cluster health instead](https://elasticsearch-py.readthedocs.io/en/v7.15.1/api.html?highlight=health#elasticsearch.client.ClusterClient.health)?
