### ISSUE TITLE
To Alter Policy/Role Naming

### ISSUE THREAD

**Issue by kamal1004** [elastic/elastic-serverless-forwarder#368]
**Describe the enhancement:**
Option for Altering the role/policy naming will help organisations to deploy this lambda with their IAM governance policies. 
**Describe a specific use case for the enhancement or feature:**
Ex - CManaged-Policy/Role name using a prefix of CManaged.

**Comment by aspacca** [comment]
@kamal1004 
could you please explain what role/policy you would like to be able to alter the name for?

beware that the role/policy created by deploying the forwarder are meant to be managed only by the deployment CF template: if you alter them from outside it will lead to inconsistency and probably a broken deployment

or do you care just about the fact that the role/policy follows a standard naming format, or that you have a standard naming format so that you can reference them (without changing) in other IAM governance policies?

**Comment by hriprsd** [comment]
I second this @aspacca 
Could we have a way to have the roles as some type of config parameter that we pass to the lambda? maybe via config file? 
Because in orgs having rigid naming conventions/ IAM governance policies, using this is a pain with the given role names etc. 
Am i missing something here? Correct me if am wrong.

**Comment by kamal1004** [comment]
I am thinking, we could add an attribute in the publish_lambda script by which we can inject our own role/policy names.
We must ref the role/policy name where ever required in CF templates.

**Comment by aspacca** [comment]
@PeterPaulH , @kamal1004 my feeling it's that it will add too much customisation when deploying from SAR, that has already a few

I'd rather add this feature to [direct deployment](https://www.elastic.co/guide/en/esf/master/aws-deploy-elastic-serverless-forwarder.html#aws-serverless-forwarder-direct-deploy)

**Comment by aspacca** [comment]
@kamal1004 great to hear that your tests are working properly

please, feel free to open a PR with your changes to the publishing script and we can start from the to make them as much dynamic as we need

thanks :)

**Comment by kamal1004** [comment]
@aspacca I have created a PR #386  addressing this issue, Kindly review. 😄
