### ISSUE TITLE
[Potential Bug?] Elastic Forwarder Lambda timed out at config_storage.get_as_string()?

### ISSUE THREAD

**Issue by whc4017** [elastic/elastic-serverless-forwarder#497]
Not sure if it is a bug or a problem in my setup.

I am setting up elastic serverless forwarder to send cloudwatch logs from Lambda A to ELK. The forwarder is successfully triggered after invoking the lambda A, it has the IAM permission to get the `config.yaml` file in the S3. The S3 bucket is also attached a VPC endpoint. however it gets timeout error as below.
<img width="960" alt="image" src="https://github.com/elastic/elastic-serverless-forwarder/assets/61936815/24c06774-e695-4477-aea1-58d878627beb">

I tried to use logger to locate the issue, and found that the code is stuck at
`config_yaml: str = config_storage.get_as_string()` in `handlers/aws/utils.py`, as the log immediately after the config_yaml is not shown on the cloudwatch. The IDE points the method to the Protocol class, and the function does nothing.
<img width="789" alt="image" src="https://github.com/elastic/elastic-serverless-forwarder/assets/61936815/316559e4-fec3-4490-9007-fd61f4db262f">
<img width="460" alt="image" src="https://github.com/elastic/elastic-serverless-forwarder/assets/61936815/0f9feff0-0e1c-4ee9-b1a5-03cdc9ba4ce0">

Would love to know anything missing from my side, or is it a bug. Thanks a lot.

Version

**Comment by aspacca** [comment]
@whc4017 I have the impression you changed the forwarder lambda timeout to 240 seconds, is this correct?

the forwarder is designed to run with a timeout of 15 minuets. if it will process all the content before that time it will last shorter. otherwise it will reserve the last 2 minutes to handle the continuation for the remaining content sending it to the continuing queue that will trigger the lambda again

how big is the config yaml?
even with a reduced timeout it seems strange to me that it takes 4 minutes to download it. getting the config yaml from s3 is the second thing that the forwarder does just after checking the first record of the payload it was triggered by.

what's the timestamp of the previous entry in the log, it should be something like `"message":trigger", "type":...`

**Comment by whc4017** [comment]
Hi @aspacca , I found out that it is due to networking issues in AWS. Let me close the case now.

**Comment by pkward** [comment]
> Hi [@aspacca](https://github.com/aspacca) , I found out that it is due to networking issues in AWS. Let me close the case now.

Hi WHC4017, I'm actually running into the same issue. Did you have to do anything special to get resolve this issue?
