### ISSUE TITLE
SAR: Gracefull handling of error scenarios

### ISSUE THREAD

**Issue by ravikesarwani** [elastic/elastic-serverless-forwarder#54]
Handle error scenarios gracefully in the Lambda function. Few scenarios comes to mind that we need to investigate and see if extra error handling code needs to be added:

- [x] Elasticsearch overloaded “(429) Too Many Requests”
- [x] Elasticsearch unreachable because of network or other errors
- [x] Some events in the bulk request failed to ingest
- [x] Failure because of format errors etc.

Some error cases can be retried and we should have optimal retry logic in the code for those.
In other cases we will need to use the DLQ and write events there so users can investigate and potentially be able to re-process

**Comment by aspacca** [comment]
We identified two kinds of failure that can happen during the execution of the Lambda:

1. Errors before the ingestion phase started
2. Errors during the ingestion phase

For errors at (1), we can safely make the Lambda return a failure: these errors are mostly due to misconfiguration, improper permission on the AWS resources, etc. Most importantly when an error occurs at this stage we don’t have any state yet about the events that are ingested, so there’s no consistency to keep and we can safely let the Lambda return a failure, with the underlying trigger ending up in a built-in retry mechanism.

For errors at (2) the situation is more tricky: we have now a state for N failed events out of total X events, if we fail the whole Lambda all the X events will be processed again. While the N failed ones could now succeed, the remaining X-N will now fail, since the datastreams are append-only and we would try to recreate already ingested documents (the ID of the document is deterministic).

The implemented solution to overcome this problem is to add an internal “reply queue”, similar to the internal continuing queue, where to store a single failed event per message that the users can optionally use to trigger the Lambda itself, or consume the messages in the way they prefer.
In the case that the reply queue is used to trigger the Lambda itself, a proper handler must be implemented.

In both cases, supporting a reply queue has the drawback of adding code to inspect every single failure in the Shippers (ie: output components in the ESF context) and handling the messaging to the reply queue.

While at the moment we support only Elasticsearch as output/shipper, the Lambda function is designed to easily support multiple outputs.

If this will be the case in the future, complexity of handling the messaging to the reply queue will grow linearly, since a single event could have different failure/success outcome for different outputs, and all of them have to be handled and sent to the reply queue separately.

Overall the concrete implementation for the Lambda in https://github.com/elastic/elastic-serverless-forwarder/pull/60 minimised the complexity with enough abstraction to have a single reply "dispatcher" that's generic enough for every shipper, and a single reply handler that will contain the concrete logic for every single shipper
