### ISSUE TITLE
SAR: Review code and documentation and fix as appropriate for automatic routing support for S3 SQS Event Notifications input

### ISSUE THREAD

**Issue by ravikesarwani** [elastic/elastic-serverless-forwarder#71]
**Based on our documentation** I see several discrepancy that we need to review/test from code and then fix both code and doc as appropriate.

- [ ] aws.ec2_logs This looks missing in our list but we have an Elastic Agent integration for this.
- [ ] aws.route53_public_logs This looks missing in our list but we have an Elastic Agent integration for this.
- [ ] aws.route53_resolver_logs This looks missing in our list but we have an Elastic Agent integration for this.
- [ ] aws.s3access This looks missing in our list but we have an Elastic Agent integration for this.
- [ ] aws.lambda This is in our list, but I see only AWS Lambda Metrics integration no logs so this probably is in there as error.
- [ ] aws.sns This is in our list, but I see only AWS SNS Metrics integration no logs so this probably is in there as error.
- [ ] aws.s3_storage_lens This is in our list, but this is a metrics integration. I am assuming we should have automatic routing support for aws.s3access logs which is missing in our list.

Review and fix code and documentation as appropriate for the support we have for automatic routing for S3 SQS Event Notifications input.

**Conclusion:**
- aws.lambda, aws.sns, and aws.s3_storage_lens are being removed. 
- We can't apply the current auto-discovery mechanism on the following log types "aws.ec2_logs, aws.route53_public_logs, aws.route53_resolver_logs, aws.s3access" and we will keep it outside of the scope of this issue.

**Comment by ravikesarwani** [comment]
cc: @aspacca

**Comment by ravikesarwani** [comment]
Here's the list of index templates that we create when users install AWS assets via integrations. So these are the ones we should support from the automatic routing perspective.
<img width="249" alt="Screen Shot 2022-02-11 at 7 32 21 PM" src="https://user-images.githubusercontent.com/64450378/153688266-4755cfb4-f8bc-400c-8bc2-1abcfa0e2aab.png">

**Comment by aspacca** [comment]
@ravikesarwani I will review the list of logs integrations and see what can we do for adding support in ESF for the missing ones.

Please consider that auto-discovery is based on the expected path of AWS logs shipped to an S3 bucket by default setup.

missing integrations might be already occur because AWS doesn't provide a default and/or unique path that's auto-discoverable when shipping to an S3 bucket

**Comment by aspacca** [comment]
These are the integrations supported in the code:

- aws.cloudtrail
- aws.cloudwatch_logs
- aws.elb_logs
- aws.firewall_logs
- aws.lambda
- aws.sns
- aws.s3_storage_lens
- aws.vpcflow
- aws.waf

`aws.s3_storage_lens` is clearly incorrect: while S3 storage lens data can be exported in CSV format to an S3 bucket with a unique path format that we can auto-discover, they are not logs, so it should be removed.


- aws.ec2_logs
- aws.route53_public_logs
- aws.route53_resolver_logs
- aws.s3access

for all this logs types AWS doesn't provide a unique/default path we can base auto-discovery one. In order to support them we should try to inspect the content of the event, solution that we decided to not pursue.

Please let me know if we should investigate if we will be able to support auto-discovery for these missing ingestions through event inspection.

**Comment by aspacca** [comment]
in case we will decide to adopt event inspection we could investigate as well to switch to this logic also for auto-discovery of the already supported integrations: for any integration were this could be possible we will enable auto-discovery feature for users with a not default ingestion path on the S3 bucket

I would rather reduce the scope of event inspection based auto-discovery to native AWS logs types anyway: while it would be possible to expand the support to a lot of different integrations (as long as their events have a unique and discoverable structure) the scope would increase a lot and I wonder if the ESF is the correct place where to handle this feature

**Comment by aspacca** [comment]
`aws.sns` is incorrect as well: SNS provide ingestion of both metrics and failure reasons logs to an S3 bucket.
the only auto-discoverable one would be the metrics one, that we have an integration for.
failure reason logs are not discoverable through path expectation and we don't have an integration for as well.
I will remove it

**Comment by aspacca** [comment]
last note: enabling auto-discovery through event inspection we will be able to support auto-discovery on inputs/triggers other than the S3 SQS event notification

**Comment by ravikesarwani** [comment]
This issue is to make sure our current method of auto-discovery is accurate from code and document perspective.
So in summary:
- `aws.sns` and `aws.s3_storage_lens` is incorrect. Let's fix that.
- What about `aws.lambda`? It's in our list in documentation. I don't see any index template for it. Can you clarify?
-  Based on your comments looks like we can't apply the current auto-discovery mechanism on the following logs: aws.ec2_logs, aws.route53_public_logs, aws.route53_resolver_logs, aws.s3access

Let's cover event based auto-discovery as a separate issue. I can open one for investigation to research and document the findings so that we can move forward with that as a separate issue.

**Comment by aspacca** [comment]
>`aws.sns` and `aws.s3_storage_lens` is incorrect. Let's fix that.

see #82 

> What about `aws.lambda`? It's in our list in documentation. I don't see any index template for it. Can you clarify?

I missed it, same as the two above, fixed in #82 as well

> Based on your comments looks like we can't apply the current auto-discovery mechanism on the following logs: aws.ec2_logs, aws.route53_public_logs, aws.route53_resolver_logs, aws.s3access

exactly

**Comment by ravikesarwani** [comment]
https://github.com/elastic/elastic-serverless-forwarder/issues/83
